### ISSUE TITLE
Classes that inherit Abstract should not require abstract class properties

### ISSUE THREAD

**Issue by wolph** [reinhrst/abstractcp#3]
Take this example:

```python
class A(abstractcp.Abstract):
    NAME: str = abstractcp.abstract_class_property(str)


class B(A, abstractcp.Abstract):
    NAME = 'class B'


class C(B):
    NAME = 'class C'
```

If `B` inherits `Abstract` you get the error that an abstract property is required. If `B` does not inherit `Abstract` you naturally get the problem that it doesn't inherit `Abstract` and doesn't implement `NAME`

**Comment by reinhrst** [comment]
This should work indeed; I'm travelling at the moment, will take a look at the end of the week. Shouldn't be too hard to fix I imagine.

**Comment by wolph** [comment]
Sorry, I think the issue was slightly different actually... it was due to mixin/mro weirdness that it didn't work...

Still though, requiring abstract properties for a class to be abstract seems inconvenient:
```
class SomeAbstractClass(abstract.Abstract):
    # No abstract properties defined yet
    whatever = 123
```

**Comment by wolph** [comment]
I've updated the example showing where this goes wrong. If you're removing an abstract property from a class you also need to remove the `Abstract` class which is annoying.

**Comment by reinhrst** [comment]
Thanks, just to get the picture clear, in your updated example, the second sentence of the statement

> If B inherits Abstract you get the error that an abstract property is required. If B does not inherit Abstract you naturally get the problem that it doesn't inherit Abstract and doesn't implement NAME

is not true anymore right?

As in: class B will give an error, class C will not.


If I understand the problem correctly, this is by design. I believe strongly in the [zen of python](https://www.python.org/dev/peps/pep-0020/); this choice ticks in my mind both "Explicit is better than implicit." and "Errors should never pass silently." -- although, as probably with many Zen's, I'm sure one could also argue the other way. It is to make clear, in one glance, whether a class is abstract or not.

If you have a good use-case on why you would want to have a non-abstract class but make it directly inherit `acp.Abstract`, I could imagine looking into some sort of silencer for this error.

(BTW: it's been a couple of months since I looked at this code, so there may be even other, technical, reasons for this choice; however I do remember explicitly making this choice)

**Comment by wolph** [comment]
I'm a big follower of PEP20 as well, which is why I invoke this part: There should be one-- and preferably only one --obvious way to do it.

Not having an abstract property in an abstract class should not be considered an error since abc.ABC would not raise an error either.

Especially during development it can often occur that you comment out a property temporarily and/or replace it with a constant, having to remove the inherited class as well is an unneeded annoyance.

**Comment by wolph** [comment]
> > If B inherits Abstract you get the error that an abstract property is required. If B does not inherit Abstract you naturally get the problem that it doesn't inherit Abstract and doesn't implement NAME
> 
> is not true anymore right?
> 
> As in: class B will give an error, class C will not.

Correct. 

I should note that I'm not looking for a non-abstract class that inherits Abstract, but even an abstract class should be able to have some non-abstract properties.

**Comment by reinhrst** [comment]
I think the nicest solution will be to change the TypeError to  a warning. After all, all I want to do is to warn the developer that they're probably forgetting something. If one really wants to, they can ignore the warning.

I do agree that the `abc` module doesn't enforce abstract classes to have abstract methods; on the other hand, it could not really do this. Since inheriting from `abc.ABC` applies to that class and all subclasses (some of which ought to be non-abstract to make any sense), it wouldn't really work. In this module, only classes having `acp.Abstract` as direct parent are considered abstract (so here it can be enforced).

Anyways, I think a warning is useful in most cases (as you admitted yourself, you only ran into this issue because some mixin-stuff that did something else from what you expected, in which case a warning comes in handy). I agree that it's bothersome to get an exception if you just comment out something, so a warning would work nicely then. And if someone really wants to silence the whole thing, it's only 2 lines of code (which I added to the readme).

**Comment by reinhrst** [comment]
Version 0.9.9 with this fix is live on pypi

**Comment by wolph** [comment]
Fantastic! Thank you :)
